#server.port=9009
#logging.config: classpath:logback.xml
server:
  port: 8081
  servlet.context-path: /pns
spring.data.mongodb.uri: mongodb+srv://pritamadmin:adminpritam@cluster0.y4hyl.mongodb.net/<dbname>?retryWrites=true&w=majority
keycloak:
    auth-server-url: http://localhost:8080/auth
    realm: PNS_REALM
    resource: pns-contract-mangement
    public-client: true
    principal-attribute: preferred_username
app:
    database.name: userdb
    switch:
      index.update:
         customer: true
         contract: true
         equipment: true
         equipmentDetails: true
    page.size:
      customer: 4
      equipment: 6
      contract: 3
    index:
      name:
         customer: customers
         contract: contracts
         equipment: equipments
         equipmentItem: equipmentItems
