logging.config: /pns/config/log/contract-management/logback.xml
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB      max-request-size: 5MB  application.name : contract-management
server:
  port: 8081
  servlet.context-path: /pns
spring.data.mongodb.uri: mongodb+srv://pritamadmin:adminpritam@cluster0.y4hyl.mongodb.net/<dbname>?retryWrites=true&w=majority
keycloak:
    auth-server-url: https://pns.southeastasia.cloudapp.azure.com/auth
    realm: PNS_REALM
    resource: pns-contract-mangement
    principal-attribute: preferred_username
    credentials:        secret: d1c07de3-8705-42e1-9169-b31934f353f2
app:
    employee.id.length : 7
    database.name:
    contract: userdb
    userprofile: userprofile
    print.jasper:
        compiled: true
        file.url: /pns/config/application/${spring.application.name}/PnsContractInvoice.jasper
    holiday.file.url: /pns/config/application/${spring.application.name}/holiday.xlsx
    switch:
        index.update:
            customer: true
            contract: true
            equipment: true
            equipmentDetails: true
            employee.profile: true
    page.size:
        customer: 4
        equipment: 6
        contract: 3
        employee.profile: 10
    index:
        name:
        customer: customers
        contract: contracts
        equipment: equipments
        equipmentItem: equipmentItems
        employee:
            profile: employeeProfiles
            leaveQuota: leaveQuota
            leaveHistory: leaveHistory
    leave.quota.total:
        cl: 20
        pl: 20    
        sl: 30
    smtp:
        username: "smtp.pritam@gmail.com"
        password: Pass@M10340791
        port: "587"
        host: "smtp.gmail.com"